# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3ac2de9c0a4a773943c4489e917d619c093e893d8587819ce808d0773bd32d516752d1dd6905f994f53788eee3809df04c3abb270d5a07851f7de952e2669b1

test:
  secret_key_base: 8e3c89f1bf1ffeb441f71e5fbe8026fd9dd02c65fc03e8b6d8cf4952e36efd15e97236a67f8d187a71f4a1c432e8b02d1ff1e5df89d1a9ff03f1312c38de8c57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
